openapi: 3.0.1
info:
  title: discrete-agent
  description: basic template for map colonies service
  version: 1.6.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /trigger:
    post:
      operationId: CreateLayer
      tags:
        - ManualTrigger
      summary: trigger layer creation from source directory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createLayerRequest'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /status:
    get:
      operationId: getWatchStatus
      tags:
        - WatchStatus
      summary: returns the watching status of the agent.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/watchStatus'
  /status/start:
    post:
      operationId: startWatching
      tags:
        - WatchStatus
      summary: starts the agent file watcher.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/watchStatus'
  /status/stop:
    post:
      operationId: stopWatching
      tags:
        - WatchStatus
      summary: stops the agent file watcher.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/watchStatus'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    createLayerRequest:
      type: object
      required:
        - sourceDirectory
      properties:
        sourceDirectory:
          description: layer root directory relative to mount directory
          type: string
    watchStatus:
      type: object
      properties:
        watching:
          type: boolean
